# k8s-app.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: app-1
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  selector:
    app: app-1
  ports:
  - port: 3001
    protocol: TCP
    nodePort: 30000
  type: LoadBalancer